name: test-fice
on: [push]
jobs:

  fice-install:
    name: Install fenics_ice
    runs-on: ubuntu-latest

    steps:

      # Get fice code
      - uses: actions/checkout@v2

      # Get micromamba & prerequisites
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: anaconda-client-env
          use-mamba: true

      - name: Install Conda environment from environment.yml
        # if: steps.cache-conda.outputs.cache-hit != 'true'
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-name: fenics_ice
          environment-file: environment.yml
          channel-priority: strict
          #auto-update-conda: true
          #use-only-tar-bz2: true # necessary for caching

      # Get conda info
      - name: mamba info
        shell: bash -l {0}
        run: |
          micromamba info -a
          micromamba list
          micromamba config --show-sources
          micromamba config --show
