name: test-fice
on: [push]
jobs:

  fice-install:
    name: Install fenics_ice
    runs-on: ubuntu-latest

    steps:

      # Get fice code
      - uses: actions/checkout@v2

      # Get miniconda & prerequisites
      # TODO cache! https://github.com/marketplace/actions/setup-miniconda
      - name: Cache conda
        id: cache-conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yml') }}

      - name: Install Miniconda
        # if: steps.cache-conda.outputs.cache-hit != 'true'
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: fenics_ice
          environment-file: environment.yml
          channel-priority: strict
          auto-update-conda: true
          use-only-tar-bz2: true # necessary for caching

      # Get conda info
      - name: Conda info
        shell: bash -l {0}
        run: |
          conda info -a
          conda list
          conda config --show-sources
          conda config --show
